# Generated by Django 3.1.4 on 2020-12-29 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='balance',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='you dont have enough budget')]),
        ),
    ]
