# Generated by Django 3.1.4 on 2020-12-30 06:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0003_auto_20201229_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='you should enter a valid amount')]),
        ),
        migrations.AlterField(
            model_name='department',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='you dont have enough budget to raise fund')]),
        ),
        migrations.AlterField(
            model_name='head',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
