# Generated by Django 3.1.4 on 2020-12-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20201230_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='join_date',
            field=models.DateField(),
        ),
    ]
