# Generated by Django 3.1.4 on 2020-12-30 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0005_auto_20201230_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator.department'),
        ),
        migrations.AlterUniqueTogether(
            name='head',
            unique_together={('user', 'department')},
        ),
    ]
