# Generated by Django 3.1.4 on 2020-12-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20201230_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-date']},
        ),
    ]
