# Generated by Django 3.1.4 on 2020-12-30 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='expense',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
