# Generated by Django 3.1.4 on 2020-12-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20201231_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
