# Generated by Django 3.1.4 on 2020-12-31 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_expense_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-timestamp']},
        ),
    ]
